kobapay/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import CustomLoginView, CustomLogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paycash.urls')),
    path('accounts/login/', CustomLoginView.as_view(), name='account_login'),
    path('accounts/logout/', CustomLogoutView.as_view(), name='account_logout'),
    path('accounts/', include('allauth.urls')),
]

paycash/urls.py
from django.urls import path
from . import views

app_name = 'paycash'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('home/', views.HomeView.as_view(), name="home"),
    path('history/', views.HistoryView.as_view(), name="history"),
    path('detail/<int:pk>/', views.DetailView.as_view(), name="detail"),
    path('charge/', views.ChargeView.as_view(), name="charge"),
    path('pay/', views.PayView.as_view(), name="pay"),
    path('send/', views.SendView.as_view(), name="send"),
    path('update/<int:pk>/', views.UpdateView.as_view(), name="update"),
    path('delete/<int:pk>/', views.DeleteView.as_view(), name="delete"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    total_amount = models.IntegerField(blank=True, null=False, default=0)
    
    class Meta:
        verbose_name_plural = 'CustomUser'

paycash/models.py
from django.db import models
from accounts.models import CustomUser

class Deal(models.Model):
    DEAL_CHOICES = [
        ('C', 'Charge'),
        ('P', 'Pay'),
        ('S', 'Send'),
        ('R', 'Recieve'),
    ]

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    deal_type = models.CharField(verbose_name='取引タイプ', choices=DEAL_CHOICES)
    deal_user = models.CharField(verbose_name='取引ユーザー', blank=True, null=True)
    amount = models.IntegerField(verbose_name='金額', blank=False, null=False)
    content = models.TextField(verbose_name='内容', blank=True, null=True)
    deal_check = models.BooleanField(verbose_name="完了チェック", blank=True, null=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)

    class Meta:
        verbose_name_plural = 'Deal'

    def __str__(self):
        return str(self.id)

accounts/forms.py
from django import forms
from allauth.account.forms import SignupForm, LoginForm

class CustomSignupForm(SignupForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['email'].label = "Eメールアドレス"
        self.fields['username'].label = "ユーザー名"
        self.fields['password1'].label = "パスワード"
        self.fields['password2'].label = "パスワード（確認）"

        self.fields['email'].widget.attrs['placeholder'] = "email"
        self.fields['username'].widget.attrs['placeholder'] = "username"
        self.fields['password1'].widget.attrs['placeholder'] = "password"
        self.fields['password2'].widget.attrs['placeholder'] = "possword"

class CustomLoginForm(LoginForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['login'].label = "Eメールアドレス or ユーザー名"
        self.fields['password'].label = "パスワード"

        self.fields['login'].widget.attrs['placeholder'] = "email or username"
        self.fields['password'].widget.attrs['placeholder'] = "password"

paycash/forms.py
from django import forms
from .models import Deal

class BankDealForm(forms.ModelForm):
    class Meta:
        model = Deal
        fields = ('amount', 'content')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

class UserDealForm(forms.ModelForm):
    class Meta:
        model = Deal
        fields = ('amount', 'deal_user', 'content')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

accounts/views.py
from django.shortcuts import render
from allauth.account.views import LoginView, LogoutView
from allauth.account.forms import LoginForm
from django.contrib import messages

class CustomLoginView(LoginView):
    template_name = "account/login.html"
    form_class = LoginForm

    def form_valid(self, form):
        response = super().form_valid(form)
        storage = messages.get_messages(self.request)
        list(storage)
        return response
    
class CustomLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        storage = messages.get_messages(request)
        list(storage)
        return response

paycash/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404
from django.core.exceptions import PermissionDenied
from .models import Deal
from .forms import BankDealForm, UserDealForm

class OnlyYouMixin(UserPassesTestMixin):
    raise_exception = True

    def test_func(self):
        deal = get_object_or_404(Deal, pk=self.kwargs['pk'])
        return self.request.user == deal.user

class IndexView(generic.TemplateView):
    template_name = "index.html"

class HomeView(LoginRequiredMixin, generic.TemplateView):
    template_name = "home.html"

class HistoryView(LoginRequiredMixin, generic.ListView):
    model = Deal
    template_name = 'history.html'

    def get_queryset(self):
        deals = Deal.objects.filter(user=self.request.user).order_by('-updated_at')
        return deals
    
class DetailView(LoginRequiredMixin, OnlyYouMixin, generic.DetailView):
    model = Deal
    template_name = 'detail.html'

class ChargeView(LoginRequiredMixin, generic.CreateView):
    model = Deal
    template_name = 'charge.html'
    form_class = BankDealForm
    success_url = reverse_lazy('paycash:history')

    def form_valid(self, form):
        deal = form.save(commit=False)
        deal.user = self.request.user
        deal.deal_type = 'C'
        deal.save()

        user = self.request.user
        user.total_amount += deal.amount
        user.save()
        
        messages.success(self.request, 'Charge取引が完了しました。')
        return super().form_valid(form)
    
class PayView(LoginRequiredMixin, generic.CreateView):
    model = Deal
    template_name = 'pay.html'
    form_class = BankDealForm
    success_url = reverse_lazy('paycash:history')

    def form_valid(self, form):
        deal = form.save(commit=False)
        deal.user = self.request.user
        deal.deal_type = 'P'
        deal.save()

        user = self.request.user
        user.total_amount -= deal.amount
        user.save()

        messages.success(self.request, 'Pay取引が完了しました。')
        return super().form_valid(form)
    
class UpdateView(LoginRequiredMixin, OnlyYouMixin, generic.UpdateView):
    model = Deal
    template_name = 'update.html'
    form_class = BankDealForm

    def get_success_url(self):
        return reverse_lazy('paycash:detail', kwargs={'pk': self.kwargs['pk']})
    
    def form_valid(self, form):
        user = self.request.user
        before_deal = Deal.objects.get(pk=form.instance.pk)
        after_deal = form.instance

        if before_deal.deal_type == 'C':
            user.total_amount -= before_deal.amount
            user.total_amount += after_deal.amount
            user.save()
        elif before_deal.deal_type == 'P':
            user.total_amount += before_deal.amount
            user.total_amount -= after_deal.amount
            user.save()

        messages.success(self.request, '取引情報を更新しました。')
        return super().form_valid(form)
    
    def form_invalid(self, form):
        messages.error(self.request, '取引情報の更新に失敗しました。')
        return super().form_invalid(form)
    
class DeleteView(LoginRequiredMixin, OnlyYouMixin, generic.DeleteView):
    model = Deal
    template_name = 'delete.html'
    success_url = reverse_lazy('paycash:history')

    def form_valid(self, form):
        user = self.request.user
        deal = self.object

        if deal.deal_type == 'C':
            user.total_amount -= deal.amount
            user.save()
        elif deal.deal_type == 'P':
            user.total_amount += deal.amount
            user.save()

        messages.success(self.request, f'取引#{ deal.pk }を削除しました。')
        return super().form_valid(form)
    
class SendView(LoginRequiredMixin, generic.CreateView):
    model = Deal
    template_name = 'send.html'
    form_class = UserDealForm
    success_url = reverse_lazy('paycash:history')

    def form_valid(self, form):
        deal = form.save(commit=False)
        deal.user = self.request.user
        deal.deal_type = 'S'
        deal.save()

        user = self.request.user
        user.total_amount -= deal.amount
        user.save()

        messages.success(self.request, 'Pay取引が完了しました。')
        return super().form_valid(form)

paycash/templates/base.html
{% load static %}

<html lang="ja">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="robots" content="noindex">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://unpkg.com/ress/dist/ress.min.css">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        {% block head %}{% endblock %}
    </head>
    <body>
        {% if user.is_authenticated %}
        <header>
            <nav>
                <ul class="nav-list">
                    <li><a class="btn" href="{% url 'paycash:home' %}">Dashboard</a></li>
                </ul>
                <a class="btn" href="{% url 'account_logout' %}">Signout</a>
            </nav>
        </header>
        {% endif %}
        {% block contents %}{% endblock %}
        <footer>
            <div class="copyright">
                <small>&copy; 2025 KobaPay</small>
            </div>
        </footer>
    </body>
</html>

paycash/templates/charge.html
{% extends "base.html" %}
{% load static %}

{% block title %}Charge{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/deal.css' %}">
{% endblock %}

{% block contents %}
<div style="margin-top:1rem"></div>
<h1 class="main-title">Charge</h1>
<div style="margin-top:2.5rem"></div>
<div class="block">
    {% for field in form %}
        {% for error in field.errors %}
            <p class="message error">{{ field.label }}: {{ error }}</p>
            <div style="margin-bottom:.5rem"></div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <p class="message error">{{ error }}</p>
        <div style="margin-botton:.5rem"></div>
    {% endfor %}
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            {{ form.amount.label_tag }}
            {{ form.amount }}
        </div>
        <div style="margin-top:1rem"></div>
        <div class="form-group">
            {{ form.content.label_tag }}
            {{ form.content }}
        </div>
        <div style="margin-top:2rem"></div>
        <button type="submit" class="btn">続ける</button>
    </form>
</div>
<div style="margin-top:5rem"></div>
<div style="flex:1"></div>
{% endblock %}

paycash/templates/delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}取引削除{% endblock %}

{% block head %}
<link rel="stylesheet", href="{% static 'css/delete.css' %}">
{% endblock %}

{% block contents %}
<div style="margin-top:1rem"></div>
<h1 class="main-title">取引削除</h1>
<p class="id-text">#{{ object.id }}</p>
<div style="margin-top:5rem"></div>
<div class="block">
    <form method="post">
        {% csrf_token %}
        <h1 class="label-text">本当に削除しますか？</h1>
        <div style="margin-top:2rem"></div>
        <button class="btn success" type="submit">削除</button>
        <div style="margin-top:1rem"></div>
        <a class="btn error" href="{% url 'paycash:detail' object.pk %}">キャンセル</a>
    </form>
</div>
<div style="margin-top:5rem"></div>
<div style="flex:1"></div>
{% endblock  %}

paycash/templates/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}取引詳細{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}

{% block contents %}
<div style="margin-top:1rem"></div>
<h1 class="main-title">取引詳細</h1>
<p class="id-text">#{{ object.id }}</p>
<div style="margin-top:1rem"></div>
<div class="block">
    {% if messages %}
        {% for message in messages %}
            <p class="message {{ message.tags }}">{{ message }}</p>
            <div style="margin-bottom:.5rem"></div>
        {% endfor %}
        <div style="margin-top:2rem"></div>
    {% endif %}
</div>
<div style="width:80vw" class="block">
    <div class="button-group">
        <a class="update-button" href="{% url 'paycash:update' object.pk %}">更新</a>
        <a class="delete-button" href="{% url 'paycash:delete' object.pk %}">削除</a>
    </div>
</div>
<div style="margin-top:2rem"></div>
<h1 class="dealtype-text">{{ object.get_deal_type_display }}</h1>
<div style="margin-top:1rem"></div>
<hr style="width:80vw;margin:0 auto">
<div style="margin-top:1rem"></div>
<h1 class="label-text">金額：<span style="margin-left:1rem"></span>¥ {{ object.amount }}</h1>
<div style="margin-top:1rem"></div>
<hr style="width:80vw;margin:0 auto">
<div style="margin-top:1rem"></div>
<h1 class="label-text">内容</h1>
<div style="margin-top:.5rem"></div>
<div class="container">
    <p class="content-text">{{ object.content }}</p>
</div>
<div style="margin-top:1rem"></div>
<hr style="width:80vw;margin:0 auto">
<div style="margin-top:1rem"></div>
<p class="datetime-text">{{ object.updated_at }}</p>
<div style="margin-top:5rem"></div>
<div style="flex:1"></div>
{% endblock %}

paycash/templates/history.html
{% extends "base.html" %}
{% load static %}

{% block title %}取引履歴{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/history.css' %}">
{% endblock %}

{% block contents %}
<div style="margin-top:1rem"></div>
<h1 class="maintitle">取引履歴</h1>
<div style="margin-top:2rem"></div>
<div class="block">
    {% if messages %}
        {% for message in messages %}
            <p class="message {{ message.tags }}">{{ message }}</p>
            <div style="margin-bottom:.5rem"></div>
        {% endfor %}
        <div style="margin-top:2rem"></div>
    {% endif %}
    {% if deal_list|length == 1 %}
        <a class="btn tile both" href="{% url 'paycash:detail' deal_list.0.pk %}">
            <h1 class="list-title">
                {{ deal_list.0.get_deal_type_display }} ¥ {{ deal_list.0.amount }}
            </h1>
            <div style="margin-top:.5rem"></div>
            <p class="list-content">
                {{ deal_list.0.content|truncatechars:20 }}
            </p>
            <div style="margin-top:.5rem"></div>
            <p class="list-datetime">
                {{ deal_list.0.updated_at }}
            </p>
        </a>
    {% else %}
        {% for deal in deal_list %}
            {% if forloop.first %}
                <a class="btn tile top" href="{% url 'paycash:detail' deal.pk %}">
                    <h1 class="list-title">
                        {{ deal.get_deal_type_display }} ¥ {{ deal.amount }}
                    </h1>
                    <div style="margin-top:.5rem"></div>
                    <p class="list-content">
                        {{ deal.content|truncatechars:20 }}
                    </p>
                    <div style="margin-top:.5rem"></div>
                    <p class="list-datetime">
                        {{ deal.updated_at }}
                    </p>
                </a>
            {% elif forloop.last %}
                <a class="btn tile bottom" href="{% url 'paycash:detail' deal.pk %}">
                    <h1 class="list-title">
                        {{ deal.get_deal_type_display }} ¥ {{ deal.amount }}
                    </h1>
                    <div style="margin-top:.5rem"></div>
                    <p class="list-content">
                        {{ deal.content|truncatechars:20 }}
                    </p>
                    <div style="margin-top:.5rem"></div>
                    <p class="list-datetime">
                        {{ deal.updated_at }}
                    </p>
                </a>
            {% else %}
                <a class="btn tile" href="{% url 'paycash:detail' deal.pk %}">
                    <h1 class="list-title">
                        {{ deal.get_deal_type_display }} ¥ {{ deal.amount }}
                    </h1>
                    <div style="margin-top:.5rem"></div>
                    <p class="list-content">
                        {{ deal.content|truncatechars:20 }}
                    </p>
                    <div style="margin-top:.5rem"></div>
                    <p class="list-datetime">
                        {{ deal.updated_at }}
                    </p>
                </a>
            {% endif %}
        {% endfor %}
    {% endif %}
</div>
<div style="margin-top:5rem"></div>
<div style="flex:1"></div>
{% endblock %}

paycash/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %}ホーム{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block contents %}
<div style="margin-top:1rem"></div>
<h1 class="maintitle">ホーム</h1>
<div style="margin-top:2rem"></div>
<p class="total-text">¥ {{ user.total_amount }}</p>
<div style="margin-top:3rem"></div>
<div class="container">
    <a class="btn tile top" href="{% url 'paycash:charge' %}">Charge</a>
    <a class="btn tile" href="{% url 'paycash:pay' %}">Pay</a>
    <a class="btn tile bottom" href="{% url 'paycash:history' %}">取引履歴</a>
</div>
<div style="flex:1"></div>
{% endblock  %}

paycash/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}KobaPay{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block contents %}
<div style="margin-top:8rem"></div>
<div class="container">
    <div class="inner">
        <h1 class="maintitle">KobaPay</h1>
        <div style="margin-top:.5rem"></div>
        <p class="subtext">トイチ</p>
        <div style="margin-top:5rem;"></div>
        <div class="object-center">
            <a class="btn primary" href="{% url 'account_login' %}">サインイン</a>
        </div>
        <div style="margin-top:2rem"></div>
        <div class="object-center">
            <a class="btn primary" href="{% url 'account_signup' %}">サインアップ</a>
        </div>
    </div>
</div>
<div style="margin-top:5rem"></div>
<div style="flex:1"></div>
{% endblock %}

paycash/templates/pay.html
{% extends "base.html" %}
{% load static %}

{% block title %}Pay取引{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/deal.css' %}">
{% endblock %}

{% block contents %}
<div style="margin-top:1rem"></div>
<h1 class="main-title">Pay</h1>
<div style="margin-top:2.5rem"></div>
<div class="block">
    {% for field in form %}
        {% for error in field.errors %}
            <p class="message error">{{ field.label }}: {{ error }}</p>
            <div style="margin-bottom:.5rem"></div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <p class="message error">{{ error }}</p>
        <div style="margin-botton:.5rem"></div>
    {% endfor %}
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            {{ form.amount.label_tag }}
            {{ form.amount }}
        </div>
        <div style="margin-top:1rem"></div>
        <div class="form-group">
            {{ form.content.label_tag }}
            {{ form.content }}
        </div>
        <div style="margin-top:2rem"></div>
        <button type="submit" class="btn">Pay</button>
    </form>
</div>
<div style="margin-top:5rem"></div>
<div style="flex:1"></div>
{% endblock %}

paycash/templates/send.html
{% extends "base.html" %}
{% load static %}

{% block title %}Send取引{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/send.css' %}">
{% endblock %}

{% block contents %}
{% endblock %}

paycash/templates/update.html
{% extends "base.html" %}
{% load static %}

{% block title %}取引編集{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/deal.css' %}">
{% endblock %}

{% block contents %}
<div style="margin-top:1rem"></div>
<h1 class="main-title">取引編集</h1>
<div style="margin-top:2rem"></div>
<h1 class="dealtype-text">{{ object.get_deal_type_display }}</h1>
<div style="margin-top:1rem"></div>
<hr style="width:80vw;margin:0 auto">
<div style="margin-top:1rem"></div>
<div class="block">
    {% for field in form %}
        {% for error in field.errors %}
            <p class="message error">{{ field.label }}: {{ error }}</p>
            <div style="margin-bottom:.5rem"></div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <p class="message error">{{ error }}</p>
        <div style="margin-botton:.5rem"></div>
    {% endfor %}
    <form method="post" novalidate>
        {% csrf_token %}
        <div class="form-group">
            {{ form.amount.label_tag }}
            {{ form.amount }}
        </div>
        <div style="margin-top:1rem"></div>
        <div class="form-group">
            {{ form.content.label_tag }}
            {{ form.content }}
        </div>
        <div style="margin-top:2rem"></div>
        <button type="submit" class="btn success">更新</button>
        <div style="margin-top:1rem"></div>
        <a class="btn error" href="{% url 'paycash:detail' object.pk %}">キャンセル</a>
    </form>
</div>
<div style="margin-top:5rem"></div>
<div style="flex:1"></div>
{% endblock %}